name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      release:
        description: 'upload firmware to release [true/false]'
        required: false
        default: 'true'
      release_note:
        description: 'release note'
        required: false
        default: 'update'

env:
  SOURCE_URL: https://github.com/coolsnowwolf/lede
  SOURCE_BRANCH: master
  CONFIG_URL: https://github.com/EnnawYang/openwrt-config
  CONFIG_BRANCH: lean-lede
  TOOLCHAIN_PREFIX: coolsnowwolf-lede-master
  TOOLCHAIN_TAG: toolchain
  RELEASE_BRANCH: main
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  Notification: true
  TZ: Asia/Shanghai

jobs:
  Build_OpenWrt:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config_name: [x86_64, Rpi-4B, Newifi-D2, RM2100]
        # Ref: https://github.com/EnnawYang/openwrt-config

    steps:
    - name: Free up space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 256
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # docker image prune -a -f
        # sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install tzdata $(curl -fsSL git.io/depends-ubuntu-2004) libfuse-dev rdate
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
        sudo dpkg-reconfigure -f noninteractive tzdata
        echo "DEVICE_NAME=${{ matrix.config_name }}" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
        export SOURCE_USER="$(echo $SOURCE_URL | awk -F '/' '{print $(NF-1)}')"
        echo "SOURCE_USER=$SOURCE_USER" >> $GITHUB_ENV
        export SOURCE_NAME="$(echo $SOURCE_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_NAME=$SOURCE_NAME" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@main

    - name: Check space usage before Compile
      if: (!cancelled())
      run: df -hT

    - name: Clone Source Code
      id: clone
      if: (!cancelled())
      run: |
        cd $GITHUB_WORKSPACE
        git clone $CONFIG_URL -b $CONFIG_BRANCH openwrt-config --single-branch
        cd openwrt-config
        echo "CONFIGROOT=$PWD" >> $GITHUB_ENV
        cd $GITHUB_WORKSPACE
        git clone $SOURCE_URL -b $SOURCE_BRANCH openwrt --single-branch
        cd openwrt
        echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV

    - name: Compare Toolchain Hash
      id: compare
      run: |
        cd $OPENWRTROOT
        export CURRENT_HASH=$(git log --pretty=tformat:"%h" -n1 tools toolchain)
        echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV
        echo "CURRENT_HASH is $CURRENT_HASH"
        export CACHE_HASH=$(curl -fSsL https://github.com/EnnawYang/OpenWrt-Toolchain-Cache/releases/download/$TOOLCHAIN_TAG/cache-hash.txt)
        echo "CACHE_HASH is $CACHE_HASH"
        if [ -z "$CACHE_HASH" ] || [ "$CURRENT_HASH" != "$CACHE_HASH" ]; then
          echo "::set-output name=COMPILE_TOOLCHAIN::true"
        else
          echo "::set-output name=COMPILE_TOOLCHAIN::false"
        fi

    - name: Install Feeds
      id: feeds
      if: steps.clone.conclusion == 'success' && !cancelled()
      run: |
        cd $OPENWRTROOT
        ./scripts/feeds update -a 
        ./scripts/feeds install -a

    - name: Load custom configuration
      id: custom
      if: steps.feeds.conclusion == 'success' && !cancelled()
      run: |
        cd $OPENWRTROOT
        chmod +x $CONFIGROOT/*.sh
        $CONFIGROOT/"$DEVICE_NAME"-customize.sh || echo -e ""$DEVICE_NAME"-customize.sh not found or has errors"
        cp $CONFIGROOT/"$DEVICE_NAME".config .config || exit 1
        sed -i '/CONFIG_DEVEL/d;/CONFIG_CCACHE/d;/CONFIG_BUILD_LOG/d' .config
        echo -e "\nCONFIG_DEVEL=y\nCONFIG_CCACHE=y\nCONFIG_BUILD_LOG=y\nCONFIG_BUILD_LOG_DIR=\"./logs\"" >> .config
        make defconfig
        export TARGET="$(grep -v ^# .config | grep _DEVICE_ | cut -d_ -f3)"
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        export SUBTARGET="$(grep -v ^# .config | grep _DEVICE_ | cut -d_ -f4)"
        echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV

    - name: Download package
      id: download
      if: steps.custom.conclusion == 'success' && !cancelled()
      run: |
        cd $OPENWRTROOT
        make download -j16
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Fetch Cached Toolchain
      id: fetch
      if: steps.compare.outputs.COMPILE_TOOLCHAIN == 'false'
      run: |
        cd $OPENWRTROOT
        wget -c https://github.com/EnnawYang/OpenWrt-Toolchain-Cache/releases/download/$TOOLCHAIN_TAG/$TOOLCHAIN_PREFIX-$TARGET-$SUBTARGET.tar.xz -O - | tar -xJ
        find build_dir/{host*,toolchain-*} -name .built\* -exec touch {} \;
        touch staging_dir/{host*,toolchain-*,target-*}/stamp/.*
        # sed -i 's/ $(tool.*\/stamp-compile)//;' Makefile

    - name: Compile firmware (${{ matrix.config_name }})
      id: compile
      if: (!cancelled())
      run: |
        cd $OPENWRTROOT
        echo -e ">>>> $(nproc) thread compile ..."
        make -j$(nproc)

    - name: Check space usage after Compile
      if: (!cancelled())
      run: df -hT

    - name: Upload error logs
      uses: actions/upload-artifact@v2
      if: steps.compile.conclusion == 'failure' && !cancelled()
      with:
        name: Logs_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.OPENWRTROOT }}/logs

    - name: Upload bin directory
      uses: actions/upload-artifact@v2
      if: steps.compile.conclusion == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: Bin_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.OPENWRTROOT }}/bin

    - name: Organize files
      id: organize
      if: steps.compile.conclusion == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd $OPENWRTROOT/bin/targets/*/*
        rm -rf packages
        rm *.buildinfo *sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Upload firmware directory
      uses: actions/upload-artifact@v2
      if: steps.organize.conclusion == 'success' && !cancelled()
      with:
        name: Firmware_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: github.event.inputs.release == 'true' && steps.compile.conclusion == 'success' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$FILE_DATE"
        touch release.txt
        echo -e "${{ github.event.inputs.release_note }}" > release.txt

    - name: Upload firmware to release
      if: steps.tag.conclusion == 'success' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag.outputs.release_tag }}
        bodyFile: release.txt
        artifacts: ${{ env.FIRMWARE }}/*

    - name: Remove old Releases
      if: github.event.inputs.release == 'true' && !cancelled()
      uses: dev-drprasad/delete-older-releases@v0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 10
        delete_tags: true

    - name: Notification
      if: steps.compile.conclusion == 'success' && env.Notification == 'true' && !cancelled()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$DEVICE_NAME" compile succeeded" 2>&1 >/dev/null || echo "Telegram notification failed"
        # curl -s -X POST https://sctapi.ftqq.com/${{ secrets.SCTKEY }}.send?title=""$DEVICE_NAME" compile succeeded" 2>&1 >/dev/null || echo "Wechat notification failed"
