name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      release_note:
        description: 'release note'
        required: true
        default: 'update'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_FLODER: openwrt
  CONFIG_REPO: https://github.com/EnnawYang/Actions-OpenWrt
  CONFIG_BRANCH: main
  CONFIG_FLODER: Actions-OpenWrt
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  Notification: true
  TZ: Asia/Shanghai

jobs:
  x86_64:
    runs-on: ubuntu-20.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
        sudo dpkg-reconfigure -f noninteractive tzdata

    - name: Generate release tag
      id: tag
      if: (!cancelled())
      run: |
        echo "::set-output name=release_tag::TEST1"
        touch release.txt
        echo -e "${{ github.event.inputs.release_note }}" > release.txt
        touch 1.txt
        echo "1234567890" >1.txt

    - name: Upload firmware to release
      if: steps.tag.conclusion == 'success' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag.outputs.release_tag }}
        bodyFile: release.txt
        artifacts: 1.txt

    - name: Notification
      if: env.Notification == 'true' && !cancelled()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" TEST DONE." 2>&1 >/dev/null || echo "Telegram notification failed"


  x86_64_1:
    runs-on: ubuntu-20.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
        sudo dpkg-reconfigure -f noninteractive tzdata
        echo "RM_DL=${{ github.event.inputs.rm_dl }}" >> $GITHUB_ENV
        echo "TAR=${{ github.event.inputs.tar }}" >> $GITHUB_ENV

    - name: Generate release tag
      id: tag
      if: (!cancelled())
      run: |
        echo "::set-output name=release_tag::TEST1"
        touch release.txt
        echo -e "${{ github.event.inputs.release_note }}" > release.txt
        touch 2.txt
        sleep 20
        echo "0987654321" >2.txt

    - name: Upload firmware to release
      if: steps.tag.conclusion == 'success' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag.outputs.release_tag }}
        bodyFile: release.txt
        artifacts: 2.txt

    - name: Notification
      if: env.Notification == 'true' && !cancelled()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TG_CHAT_ID }} -d text=""$TARGET_NAME" TEST DONE." 2>&1 >/dev/null || echo "Telegram notification failed"